services:
  jekyll:
    build:
      context: ./docker

    volumes:
      - type: bind
        source: ./
        target: /srv/jekyll

    ports:
      - target: 4000
        published: 4000
      - target: 35729
        published: 35729
    #    command: ["jekyll", "serve", "-l"]
    environment:
      - JEKYLL_LOG_LEVEL=debug
    command: [ "jekyll", "serve", "-l", "--config", "_config.yml,_config_local.yml" ]


#    stdin_open: true
#    tty: true
#    entrypoint: ["bash"]

